kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbac-viewer
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["pods","roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbac-viewer
subjects:
- kind: ServiceAccount
  name: rbac-viewer # Name is case sensitive
  namespace: default
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: rbac-viewer # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io